print ('helo word')
print(5+2)
print('hello' , 5)
nome=input('qual seu nome ?')
idade=input('qual sua idade ? ')
peso=input('qual seu peso ?')
print(nome)
print(idade, 'anos')
print(peso, 'kg')
print('bem vindo!')
print(idade,'anos')
print(peso,'kg')
print('SEU VELHO!!!')
